# Generated by Django 4.0.5 on 2022-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('Technology', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='now')),
                ('author', models.CharField(max_length=40)),
            ],
        ),
    ]
